spring:
  application:
    name: ddd


  datasource:
    driver-class-name: org.h2.Driver
    url:  jdbc:h2:mem:testdb
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console


logging:
  level:
    org.hibernate.SQL: debug
